### ISSUE TITLE
Bug in C++ setter?

### ISSUE THREAD

**Issue by jaigak** [AutoItConsulting/text-encoding-detect#3]
I noticed that in the C++ version, the setters SetUtf16UnexpectedNullPercent and SetUtf16ExpectedNullPercent have interchanged the fields. Is this the correct behaviour?

```cpp
void TextEncodingDetect::SetUtf16UnexpectedNullPercent(int percent) 
{
	if (percent > 0 && percent < 100)
		utf16_expected_null_percent_ = percent; 
}

void TextEncodingDetect::SetUtf16ExpectedNullPercent(int percent) 
{
	if (percent > 0 && percent < 100)
		utf16_unexpected_null_percent_ = percent;
}
```

C# version:
```csharp
public double Utf16ExpectedNullPercent
{
    set
    {
        if (value > 0 && value < 100)
        {
            _utf16ExpectedNullPercent = value;
        }
    }
  }

public double Utf16UnexpectedNullPercent
{
  set
  {
    if (value > 0 && value < 100)
    {
        _utf16UnexpectedNullPercent = value;
    }
  }
}
```

**Comment by jonathanbennett73** [comment]
Ouch, good catch, Thank you! 😊

Jonathan.

From: Jaiganésh Kumaran ***@***.***>
Sent: Monday, February 27, 2023 11:36 AM
To: AutoItConsulting/text-encoding-detect ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AutoItConsulting/text-encoding-detect] Bug in C++ setter? (Issue #3)


I noticed that in the C++ version, the setters SetUtf16UnexpectedNullPercent and SetUtf16ExpectedNullPercent have interchanged the fields. Is this the correct behaviour?

void TextEncodingDetect::SetUtf16UnexpectedNullPercent(int percent)

{

        if (percent > 0 && percent < 100)

               utf16_expected_null_percent_ = percent;

}



void TextEncodingDetect::SetUtf16ExpectedNullPercent(int percent)

{

        if (percent > 0 && percent < 100)

             utf16_unexpected_null_percent_ = percent;

}

C# version:

public double Utf16ExpectedNullPercent

{

    set

    {

        if (value > 0 && value < 100)

        {

            _utf16ExpectedNullPercent = value;

        }

    }

  }



public double Utf16UnexpectedNullPercent

{

  set

  {

    if (value > 0 && value < 100)

    {

        _utf16UnexpectedNullPercent = value;

    }

  }

}
